apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: microservice-architecture:latest
        imagePullPolicy: IfNotPresent
        command: ["node", "services/order-service/server.js"]
        ports:
        - containerPort: 3003
        env:
        - name: ORDER_SERVICE_PORT
          value: "3003"
        - name: ORDER_SERVICE_HOST
          value: "0.0.0.0"
        - name: CONSUL_HOST
          value: "consul"
        - name: CONSUL_PORT
          value: "8500"
        - name: MONGODB_URI
          value: "mongodb://mongodb:27017/microservices"
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.2"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
  - port: 3003
    targetPort: 3003
  type: ClusterIP